[package]
edition = "2021"
name = "sandbox"
version = "0.1.0"

[dependencies]
merkle_tree = {path = "../merkle_tree"}
rand = "0.8.4"
scrach_json_parser = {path = "../scrach_json_parser"}

[[bin]]
name = "sandbox"
path = "src/main.rs"
